[build]
  # Build command for the frontend - Using npm ci for production reliability
  command = "cd frontend && npm ci && npm run build"
  
  # Publish directory (where the built files are located)
  publish = "frontend/dist"
  
  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version - ensuring compatibility
  NODE_VERSION = "18"
  # Use npm version 8+ for better performance
  NPM_VERSION = "8"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.github.com https://vibe-ai-backend.vercel.app;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache index.html for shorter time
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 